program/foodl/config/routes.rb
Foodl::Application.routes.draw do

  get "issues/index"

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'search#index'
 
  match '/about', to: 'home#about'
  match '/contact', to: 'home#contact'

  match '/login', to: 'users#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/reset', to: 'users#reset_password'

  match '/list', to: 'shopping_list#index'
  match '/list/add', to: 'shopping_list#create'
  match '/list/remove', to: 'shopping_list#remove'
  match '/list/addrecipe', to: 'shopping_list#add_recipe'
  match '/list/deletelist', to: 'shopping_list#delete_list'
  match '/list/addingredientfromid', to: 'shopping_list#add_ingredient_from_id'

  
  match '/recipes/images/:id', to: 'recipes#picture'

  match '/search', to: 'search#result'
  
  match '/favorites', to: 'favorites#index'
  match '/favorites/add/:id', to: 'favorites#add'
  match '/favorites/remove/:id', to: 'favorites#remove'
  
  
  match '/issues', to: 'issues#index'
  match '/issues/new', to: 'issues#new'
  match '/issues/create', to: 'issues#create'

  match '/search/autocomplete/:q', to: 'search#autocomplete_food_types'

  resources :users

end

program/foodl/app/views/layouts/_footer.html.erb
<footer>
  <nav>
  <a href="#">rapport&eacute;r fejl</a>
  <%= link_to "om foodl", :controller => "home", :action => "about" %>
  <%= link_to "kontakt foodl", :controller => "home", :action => "contact" %>
  </nav>
</footer>

<div id="chart">
<!-- chart.dk unified trackercode - v1 -->
<script src="http://www.chart.dk/js/unified.asp"></script>
<script language="javascript">
 track_visitor(151390, "");
</script>
<noscript>
 <a href="http://www.chart.dk/ref.asp?id=151390" target="_blank">
  <img src="http://cluster.chart.dk/chart.asp?id=151390" border="0" alt="Chart.dk">
 </a>
</noscript>
<!-- chart.dk unified trackercode - v1 -->
</div>

<div id="loading">
  <div class="img">
    <img src="<%=image_path "grimanimation.gif" %>" alt="Vent venligst..." />
  </div>
  <div>
    Vent venligst...
  </div>
</div>

<div id="notification">
</div>

<div id="login-reminder">
  <div class="img">
    <img src="<%=image_path "arrow.png" %>" alt="Kig her" />
  </div>
  <div>
    Husk at oprette en bruger for at gemme din indkøbsliste og favoritter.
  </div>
</div>

<script type="text/javascript">
<% flash.each do |key, value| %>
  flashMessage("<%=value.to_s.gsub('"', '\"') %>", "<%=key.to_s.gsub('"', '\"') %>", 10000);
<% end %>
<% if !logged_in? and session[:list_items] and session[:list_items].length > 1 %>
  $("#login-reminder").fadeIn(300);
<% end %>
</script>

program/foodl/app/views/layouts/_header.html.erb
<header>
  <a href="<%=url_for :controller => 'search', :action => 'index' %> ">
    <%=image_tag("header_logo.png", :alt => "Foodl") %>
  </a>
  <nav>
    <a href="<%= url_for controller: 'shopping_list', action: 'index' %>">indkøbsliste
      (<span id="num_list_items"><%= list_count %></span>)
    </a>

    <a href="<%=url_for :controller => 'favorites', :action => 'index' %>">favoritter
      (<span id="num_favorites"><%=num_favorites %></span>)
    </a>
    <% if logged_in? %>
        <%= link_to "indstillinger", edit_user_path(current_user) %>
        <%= link_to "log ud", logout_path , method: "delete" %>
    <% else %>
        <%= link_to "log ind / opret bruger", login_path %>
    <% end %>
  </nav>
</header>

<% if toolbar? %>
  <%= render 'layouts/toolbar' %>
<% end %>

<% if show_ad? %>
	<img src="http://placehold.it/728x90/dee8d9/000000&text=Reklamer!!!" alt="ad" >
<% end %>

program/foodl/app/views/layouts/_toolbar.html.erb
<div id="toolbar">
  <div id="subtoolbar">
    <div id="prep-time" class="slidertool">
      <input type="checkbox" id="min30" name="min" value="1" /><label for="min30"> &lt; 30 min. </label>
      <input type="checkbox" id="min30-60" name="min" value="2" /><label for="min30-60"> 30 - 60 min. </label>
      <input type="checkbox" id="min60" name="min" value="4" /><label for="min60"> &gt; 60 min. </label>
    </div>

    <div class="slidertool">
      <label>Antal personer: <span id="amount"> </span></label>
      <div id="amount-slider"></div>
    </div>

    <div id="sorting" class="slidertool">
      <input type="radio" id="name" name="sort" value="n" /><label for="name"> Navn </label>
      <input type="radio" id="ingredients" name="sort" value="" checked="checked" /><label for="ingredients"> Relevans </label>
      <input type="radio" id="prep" name="sort" value="p" /><label for="prep"> Tilberedningstid </label>
    </div>
  </div>
</div>

program/foodl/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <link rel="shortcut icon" href="favicon.ico" />
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,500|Titillium+Web:400,400italic,600,600italic|Crafty+Girls' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>