program/foodl/config/routes.rb
Foodl::Application.routes.draw do

  get "issues/index"

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'search#index'
 
  match '/about', to: 'home#about'
  match '/contact', to: 'home#contact'

  match '/login', to: 'users#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/reset', to: 'users#reset_password'

  match '/list', to: 'shopping_list#index'
  match '/list/add', to: 'shopping_list#create'
  match '/list/remove', to: 'shopping_list#remove'
  match '/list/addrecipe', to: 'shopping_list#add_recipe'
  match '/list/deletelist', to: 'shopping_list#delete_list'
  match '/list/addingredientfromid', to: 'shopping_list#add_ingredient_from_id'

  
  match '/recipes/images/:id', to: 'recipes#picture'

  match '/search', to: 'search#result'
  
  match '/favorites', to: 'favorites#index'
  match '/favorites/add/:id', to: 'favorites#add'
  match '/favorites/remove/:id', to: 'favorites#remove'
  
  
  match '/issues', to: 'issues#index'
  match '/issues/new', to: 'issues#new'
  match '/issues/create', to: 'issues#create'

  match '/search/autocomplete/:q', to: 'search#autocomplete_food_types'

  resources :users

end

program/foodl/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :id
  has_secure_password

  before_save { |user| user.email = email.downcase}
  before_save :create_remember_token

  validates :name, length: { maximum: 50 } #, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  has_and_belongs_to_many :favorites, :join_table => 'users_recipes', :class_name => "Recipe"

  has_many :list_items
  has_many :issues

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

program/foodl/app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController
  before_filter :logged_in_user, only: [:index, :edit, :update, :destroy] #:edit, :update
  before_filter :not_logged_in,  only: [:new]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: [:index, :destroy]

  include BCrypt

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user_created = User.new
    @user = User.new
  end

  def login
  end

  def reset_password
    @user = User.new
    if (params[:user])
      user = User.find_by_email(params[:user][:email])
      if (user)
        rand_pass = Array.new(10).map {((0..9).map{|x|x} + ('a'..'z').map{|x|x})[rand(36)]}.join
        user.password = rand_pass
        user.password_confirmation = rand_pass
        UserMailer.create_and_deliver_password_change(user, rand_pass).deliver
        user.save!
        flash[:success] = "Et nyt kodeord er blevet sendt til din email"
      else
        flash[:error] = "En bruger med den email kunne ikke findes"
      end
    end
  #  @user = User.find_by_email(params[:email])
  #  random_password = array.new(10).map {((0..9).map{|x|x} + ('a'..'z').map{|x|x})[rand(36)]}.join
  #  @user.password = random_password
  #  @user.save!
  #  Mailer.create_and_deliver_password_change(@user, random_password)
  end

  def create
    @user_created = User.new(params[:user])
    if @user_created.save
      log_in @user_created

      # Check if user has any saved items in the shopping list from session
      unless session[:list_items].nil?
        session[:list_items].map do |id, listItem|
          if id.is_a? Integer
            listItem.user = @user_created
            listItem.id = nil
            listItem.save
          end
        end
        session[:list_items] = nil
      end

      # Check if user has any saved items in the shopping list from session
      unless session[:favored].nil?
        session[:favored].each do |fav|
		  #NOTE: this is replicated in favorites_controller!
          recipe = Recipe.find_by_id(fav.to_i)
		  if recipe
		    current_user.favorites << recipe
			recipe.rating = recipe.rating ? (recipe.rating + 1) : 1
			recipe.save
		  end
        end
        session[:favored] = nil
      end

      flash[:success] = "Velkommen til foodl, #{@user_created.email.split('@')[0]}!"
      redirect_to root_path
    else
      #flash[:error] = "Lolnoob"
      render 'new'
    end
  end

  def edit
  end

  def update
    # Gets @user from correct_user
    passwordEquality = BCrypt::Password.new(@user.password_digest) == params[:user][:old_password]
    formInfo = params[:user]

    if passwordEquality and @user.update_attributes(password: formInfo[:password], password_confirmation: formInfo[:password_confirmation], email: formInfo[:email])
      flash[:success] = "Profil opdateret"
      log_in @user
      redirect_to root_path
    else
      if !passwordEquality
        flash[:error] = "Dit nuvaerende kodeord er ikke rigtigt"
      end
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Bruger slettet."
    redirect_to users_url
  end

  # Mailer? http://api.rubyonrails.org/classes/ActionMailer/Base.html
  #def forgotPassword
  #  @user = User.find_by_email(params[:email])
  #  random_password = Array.new(10).map {((0..9).map{|x|x} + ('a'..'z').map{|x|x})[rand(36)]}.join
  #  @user.password = random_password
  #  @user.save!
  #  Mailer.create_and_deliver_password_change(@user, random_password)
  #end

  private

  def not_logged_in
    redirect_to root_url, notice: "Du er allerede logget ind." if logged_in?
  end

  def logged_in_user
    redirect_to login_url, notice: "Log venligst ind." unless logged_in?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path, notice: "Det har du ikke tilladelse til" unless current_user?(@user)
  end

  def admin_user
    redirect_to root_path, notice: "Det har du ikke tilladelse til!" unless current_user.admin?
  end
end

program/foodl/app/helpers/users_helper.rb
module UsersHelper
end

program/foodl/app/views/users/edit.html.erb
<div id="Edit_page">
  <div id="Register_user">
  <h1>Opdatér din profil</h1>
  <%= form_for @user do |f| %>
    <%= render 'shared/error_messages' %>

    <div class="input">
      <%= f.email_field :email, class: "text" %>
    </div>

    <div class=input>
      <%= f.password_field :old_password, class: "text", placeholder: "Nuværende kodeord" %>
    </div>

    <div class="input">
      <%= f.password_field :password, class: "text", placeholder: "Nyt kodeord" %>
    </div>

    <div class="input">
      <%= f.password_field :password_confirmation, class: "text", placeholder: "Bekræft nyt kodeord" %>
    </div>

    <div class="actions">
      <%= f.submit "Gem ændringer", class: "button" %>
    </div>
  <% end %>
  </div>
  <div id="pinapple">
    <%=image_tag "pineapple.png" %>
  </div>
</div>

program/foodl/app/views/users/index.html.erb
<% provide(:title, 'Brugere') %>
<h1>Alle brugere</h1>

<!-- # TODO: Lav noget smartere, end med if-statement, se usersController -->
<ul class="users">
  <% @users.each do |user| %>
      <li>
        <%= link_to user.email, user %>
        <% if current_user.admin? && !current_user?(user) %>
          | <%= link_to "slet", user, method: :delete,
                                      data: {confirm: "Er du sikker?" } %>
        <% end %>
      </li>
  <% end %>
</ul>

program/foodl/app/views/users/new.html.erb
<% provide(:title, 'Opret/Login ') %>
<div id="Login_page">
  <div id="Register_user">
    <h1>
      Opret bruger
    </h1>
    <%= form_for @user_created do |f| %>
      <%= render 'shared/error_messages_create'%>
    <div class="input">
      <%= f.email_field(:email, :class => "text", :placeholder => "Email") %>
    </div>
    <div class="input">
      <%= f.password_field(:password, :class => "text", :placeholder => "Kodeord")%>
    </div>
    <div class="input">
      <%= f.password_field(:password_confirmation, :class => "text", :placeholder => "Bekræft kodeord")%>
    </div>
    <div class="actions">
      <input type="submit" class="button" value="Opret" />
    </div>
    <% end %>
  </div>

  <div id="Login_content">
      <h1>
        Log på
      </h1>
      <%= form_for :session, url: sessions_path do |f| %>
      <%= render 'shared/error_messages'%>
      <div class="input">
        <%= f.email_field(:email, :class => "text", :placeholder => "Email", :value => params[:email])%>
      </div>
      <div class="input">
        <%= f.password_field(:password, :class => "text", :placeholder => "Kodeord")%>
      </div>
      <div class="actions">
        <input type="submit" class="button" value="Log ind" />
      </div>
      <% end %>
    <div class="links"> 
      <%=link_to "Glemt kodeord? Få hjælp her", action: :reset_password %>
    </div>
  </div>
  <div style="clear:both"> </div>
</div>

<div style="height:100%;position:absolute;top:0;left:50%;border-right:1px dashed #aba;z-index:-10;"></div>

program/foodl/app/views/users/reset_password.html.erb
<div id="Edit_page">
  <div id="Register_user">
  <h1>Glemt kodeord?</h1>
  <p>Skriv din email i feltet herunder for at få tilsendt et nyt kodeord.</p>
  <%= form_for @user, url: {action: :reset_password} do |f| %>

    <div class="input">
      <%= f.email_field :email, class: "text" %>
    </div>

    <div class="actions">
      <%= f.submit "Send kode", class: "button" %>
    </div>
  <% end %>
  </div>
  <div id="pinapple">
    <%=image_tag "pineapple.png" %>
  </div>
</div>

program/foodl/app/views/users/show.html.erb
<% provide(:title, 'Brugere') %>
<%= @user.name %>, <%= @user.email %>